//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMSWpfApplication
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Admission
    {
        public int AdmisionID { get; set; }
        public string RoomNo { get; set; }
        public string DateIN { get; set; }
        public string DateOUT { get; set; }
        public int PatientID { get; set; }
        public int DoctorID { get; set; }
        public int WardID { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Ward Ward { get; set; }
    }
}
